### ISSUE TITLE
Action does not use github token for cloning private repo

### ISSUE THREAD

**Issue by fwilhe** [SAP/fosstars-rating-core-action#27]
Hi,

I have a repo that's not yet public (but will be in the future).

Trying to setup the fosstars action fails because despite providing a PAT to the action it fails to clone the repo

I've reproduced this in a private repo in my own namespace, the real repo is in the SAP org.

Here is the part from the log that's relevant (I think):

```
[+] Okay, we have a GitHub token, let's try to use it
[+] The default value cache doesn't exist yet: .fosstars/github_project_value_cache.json
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[+] Let's gather info and calculate a rating for:
[+]   https://github.com/fwilhe/special-system
[+] Figuring out if the project belongs to the Eclipse Software Foundation ...
[+] Figuring out how the project uses CodeQL ...
[+] Cloning https://github.com/fwilhe/special-system ...
[!] Holy Moly, CodeqlDataProvider data provider failed!
[!] The last thing that it said was
java.io.IOException: Could not clone repository!
	at com.sap.oss.phosphor.fosstars.data.github.GitHubDataFetcher.clone(GitHubDataFetcher.java:406)
	at com.sap.oss.phosphor.fosstars.data.github.GitHubDataFetcher.loadLocalRepositoryFor(GitHubDataFetcher.java:334)
	at com.sap.oss.phosphor.fosstars.data.github.GitHubDataFetcher.localRepositoryFor(GitHubDataFetcher.java:300)
	at com.sap.oss.phosphor.fosstars.data.github.CodeqlDataProvider.fetchValuesFor(CodeqlDataProvider.java:53)
	at com.sap.oss.phosphor.fosstars.data.github.GitHubCachingDataProvider.fetchValuesFor(GitHubCachingDataProvider.java:45)
	at com.sap.oss.phosphor.fosstars.data.AbstractCachingDataProvider.doUpdate(AbstractCachingDataProvider.java:63)
	at com.sap.oss.phosphor.fosstars.data.AbstractCachingDataProvider.doUpdate(AbstractCachingDataProvider.java:20)
	at com.sap.oss.phosphor.fosstars.data.AbstractDataProvider.update(AbstractDataProvider.java:74)
	at com.sap.oss.phosphor.fosstars.data.AbstractDataProvider.update(AbstractDataProvider.java:18)
	at com.sap.oss.phosphor.fosstars.tool.SingleRatingCalculator.calculateFor(SingleRatingCalculator.java:133)
	at com.sap.oss.phosphor.fosstars.tool.AbstractHandler.process(AbstractHandler.java:266)
	at com.sap.oss.phosphor.fosstars.tool.AbstractHandler.processUrl(AbstractHandler.java:256)
	at com.sap.oss.phosphor.fosstars.tool.AbstractHandler.run(AbstractHandler.java:236)
	at com.sap.oss.phosphor.fosstars.tool.Application.run(Application.java:307)
	at com.sap.oss.phosphor.fosstars.tool.Application.main(Application.java:84)
Caused by: org.eclipse.jgit.api.errors.TransportException: https://github.com/fwilhe/special-system: Authentication is required but no CredentialsProvider has been registered
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:224)
	at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:311)
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:182)
	at com.sap.oss.phosphor.fosstars.data.github.GitHubDataFetcher.clone(GitHubDataFetcher.java:404)
	... 14 more
Caused by: org.eclipse.jgit.errors.TransportException: https://github.com/fwilhe/special-system: Authentication is required but no CredentialsProvider has been registered
	at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:678)
	at org.eclipse.jgit.transport.TransportHttp.openFetch(TransportHttp.java:465)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:142)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:94)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1309)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:213)
```

This is the workflow file I'm using

```yaml
name: 'Fosstars (Security)'
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  create_fosstars_report:
    runs-on: ubuntu-latest
    name: 'Security rating'
    steps:
      - uses: actions/checkout@v3
      - uses: SAP/fosstars-rating-core-action@v1.11.0
        with:
          report-branch: fosstars-report
          token: '${{ secrets.mytoken }}'
```

Why does it not use the provided token? Does the repo need to be public for the fosstars action to work?

**Comment by fwilhe** [comment]
Hi @sourabhsparkala, is it known/intended that the action does not work on (still) private repos? Is this an issue for the open source process? Should we just wait until our repo can be public and assume fosstars will work then?

Thanks,
Florian

**Comment by sourabhsparkala** [comment]
@fwilhe I did a quick test, I guess for private repos, this GitHub action fails. The problem as you stated the token is not being passed to the code from the secrets for a private repo.

I will need to check how to provide a fix.

Ideally this GitHub action works fine for public repos

**Comment by sourabhsparkala** [comment]
@fwilhe after a quick check, I believe that for private repos, the username with token could be mandatory. I need to check this.
